const movies = [
  {
    id: '1',
    title: 'Oceans 8',
    category: 'Comedy',
    img:"https://m.media-amazon.com/images/I/711VQcNMkvL._AC_SL1500_.jpg",
    likes: 4,
    dislikes: 1,
  },
  {
    id: '2',
    title: 'Midnight Sun',
    category: 'Comedy',
    img:"https://images-na.ssl-images-amazon.com/images/I/71-J6giZEQL.jpg",
    likes: 2,
    dislikes: 0,
  },
  {
    id: '3',
    title: 'Les indestructibles 2',
    category: 'Animation',
    img:"https://fr.web.img6.acsta.net/pictures/18/04/13/15/09/0323902.jpg",
    likes: 3,
    dislikes: 1,
  },
  {
    id: '4',
    title: 'Sans un bruit',
    category: 'Thriller',
    img:"https://fr.web.img3.acsta.net/pictures/18/03/22/16/48/2454348.jpg",
    likes: 6,
    dislikes: 6,
  },
  {
    id: '5',
    title: 'Creed II',
    category: 'Drame',
    img:"https://fr.web.img5.acsta.net/pictures/18/11/27/14/25/1451897.jpg",
    likes: 16,
    dislikes: 2,
  },
  {
    id: '6',
    title: 'Pulp Fiction',
    category: 'Thriller',
    img:"https://cdn-elle.ladmedia.fr/var/plain_site/storage/images/loisirs/cinema/news/decouvrez-quels-acteurs-auraient-du-jouer-dans-pulp-fiction-2985007/56224377-1-fre-FR/Decouvrez-quels-acteurs-auraient-du-jouer-dans-Pulp-Fiction.jpg",
    likes: 11,
    dislikes: 3,
  },
  {
    id: '7',
    title: 'Shutter Island',
    category: 'Thriller',
    img:"http://culturaddict.com/wp-content/uploads/2020/04/T2-945x1340.jpg",
    likes: 12333,
    dislikes: 32,
  },
  {
    id: '8',
    title: 'Seven',
    category: 'Thriller',
    img:"https://imgsrc.cineserie.com/2016/11/282283.jpg?ver=1",
    likes: 2,
    dislikes: 1,
  },
  {
    id: '9',
    title: 'Inception',
    category: 'Thriller',
    img:'https://fr.web.img2.acsta.net/medias/nmedia/18/72/34/14/19476654.jpg',
    likes: 2,
    dislikes: 1,
  },
  {
    id: '10',
    title: 'Gone Girl',
    category: 'Thriller',
    img:'https://fr.web.img5.acsta.net/pictures/14/09/11/17/05/508784.jpg',
    likes: 22,
    dislikes: 12,
  },
];

const movies$ = new Promise((resolve, reject) => setTimeout(resolve, 3000, movies));
export default movies$;
